packages:
  - playground
  - examples/*
patchedDependencies:
  '@vue/compiler-core@3.5.16': patches/@vue__compiler-core@3.5.16.patch
  '@vue/compiler-sfc@3.5.16': patches/@vue__compiler-sfc@3.5.16.patch
