export const cssSuggestions = [
  // 文本属性
  'text-align',
  'text-align-last',
  'text-transform',
  'text-indent',
  'text-decoration',
  'text-shadow',
  'vertical-align',
  'white-space',
  'word-spacing',
  'word-break',
  'line-height',
  'letter-spacing',

  // 字体属性
  'font',
  'font-family',
  'font-size',
  'font-style',
  'font-variant',
  'font-weight',
  'font-stretch',

  // 颜色和背景
  'color',
  'opacity',
  'background',
  'background-color',
  'background-image',
  'background-repeat',
  'background-position',
  'background-size',
  'background-clip',
  'background-origin',
  'background-attachment',
  'background-blend-mode',

  // 边框和轮廓
  'border',
  'border-width',
  'border-style',
  'border-color',
  'border-radius',
  'border-top',
  'border-right',
  'border-bottom',
  'border-left',
  'outline',
  'outline-width',
  'outline-style',
  'outline-color',
  'outline-offset',

  // 尺寸和盒模型
  'width',
  'min-width',
  'max-width',
  'height',
  'min-height',
  'max-height',
  'box-sizing',
  'margin',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'padding',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',

  // 显示和定位
  'display',
  'visibility',
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'z-index',
  'float',
  'clear',

  // 柔性盒模型
  'flex',
  'flex-grow',
  'flex-shrink',
  'flex-basis',
  'flex-flow',
  'flex-direction',
  'flex-wrap',
  'justify-content',
  'align-items',
  'align-content',
  'order',
  'align-self',

  // 网格布局
  'grid',
  'grid-template-columns',
  'grid-template-rows',
  'grid-template-areas',
  'grid-auto-columns',
  'grid-auto-rows',
  'grid-auto-flow',
  'grid-column-gap',
  'grid-row-gap',
  'grid-gap',
  'grid-column-start',
  'grid-column-end',
  'grid-row-start',
  'grid-row-end',
  'grid-area',

  // 过渡和动画
  'transition',
  'transition-property',
  'transition-duration',
  'transition-timing-function',
  'transition-delay',
  'animation',
  'animation-name',
  'animation-duration',
  'animation-timing-function',
  'animation-delay',
  'animation-iteration-count',
  'animation-direction',
  'animation-fill-mode',
  'animation-play-state',

  // 变换
  'transform',
  'transform-origin',
  'transform-style',
  'perspective',
  'perspective-origin',
  'backface-visibility',

  // 滤镜
  'filter',

  // 其他
  'cursor',
  'list-style',
  'user-select',
  'resize',
  'overflow',
  'overflow-x',
  'overflow-y',
  'box-shadow',
  'isolation',
  'mix-blend-mode',
  'content',
  'counter-reset',
  'counter-increment',
]
